[tool.poetry]
name = "aavelabyrintti"
version = "0.1.0"
description = ""
authors = ["Lotta Hyppyr√§ <lotta@hyppyra.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
